-- Petitions table (text status/priority, bigint id)
-- Run in Supabase SQL Editor. If you have an old uuid petitions table, back up data first, then:
--   drop table if exists public.petitions cascade;

create table if not exists public.petitions (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  area text,
  address text,
  category text,
  description text,
  image_url text,
  status text default 'Pending',
  priority text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  resolved_image text,
  resolution_note text,
  resolved_at timestamp with time zone
);

alter table public.petitions enable row level security;

create policy "anyone can insert petitions"
  on public.petitions for insert to anon, authenticated
  with check (true);

create policy "anyone can read petitions"
  on public.petitions for select to anon, authenticated
  using (true);

create policy "admins update petitions"
  on public.petitions for update to authenticated
  using (public.has_role(auth.uid(), 'admin'));

create policy "admins delete petitions"
  on public.petitions for delete to authenticated
  using (public.has_role(auth.uid(), 'admin'));

create index if not exists petitions_status_idx on public.petitions (status);
create index if not exists petitions_created_at_idx on public.petitions (created_at desc);
